config/routes.rb
LoginApp::Application.routes.draw do

  get "pages/home"

  get "pages/admin"
  
  post "images/createNoId"
  #get "portefolio" => "portefolio#show", :as => "portefolio"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "pages#home"
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :title, :user_id, :description, :path

  belongs_to :user
  mount_uploader :path, PhotoUploader
	

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :id, :email, :password, :password_confirmation
  
  attr_accessor :password

  has_many :images

  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user 
  end

  def self.authenticate_with_salt(id, cookie_salt)
   user = find_by_id(id)
   (user && user.password_salt == cookie_salt) ? user : nil
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    include SessionsHelper
  
  private

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  #before_filter :is_user_logged_in?, :only => [:createNoId]

  #before_filter :authenticate
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])
    @image.user_id = current_user.id
    logger.debug "The value variable x = '#{@image}'"
    respond_to do |format|
      if @image.save
        format.html { redirect_to current_user, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def createNoRedirect
    @image = Image.new(params[:image])
    @image.user_id = current_user.id
    logger.debug "The value variable x = '#{@image}'"
    respond_to do |format|
      if @image.save
        format.html { redirect_to current_user, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def createNoId
    @image = Image.new(params[:image])
    logger.debug "The value variable x = '#{@image}'"
    @image.path = PhotoUploader.new
    @image.path.cache!(params[:image])    
    #logger.debug uploader.to_yaml
    #logger.debug uploader.cache_name
     if @image.path.cached?
     #render :partial => 'imageInit', :locals => { :image => @image } 
      redirect_to root_url, :locals => { :image => @image }   
   else
    redirect_to root_url,  notice: 'Upload did not processed.'  
  end
      
end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def admin
  end

end

app/controllers/portefolio_controller.rb
class PortefolioController < ApplicationController
  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Log in"
  end

  def create
   user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
  	redirect_to root_url, :notice=> "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:show, :destroy]
  before_filter :correct_user, :only => [:show, :destroy]

  def new
  	@user = User.new
    @title = "Sign Up"
  end

  def create
  	@user = User.new(params[:user])
      if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user, :notice=>"Signed up!"
  	else
  		render "new"
  	end
  end

  def show
  	@user = User.find(params[:id])
  	@images = @user.images
  end

  def destroy
  	@user = User.find(params[:id])
  	
  	if @user.destroy
  	  reset_session
  	  redirect_to root_url, :notice=> "The account has been destroyed !" 
  	else
  	  redirect_to root_url, :notice=> "No destruction"	
  	end
  end

   private
    
    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/images_helper.rb
module ImagesHelper

	def is_user_logged_in?
	  	if current_user?(@user)
	  		mount_uploader :path, PhotoUploader
	  	else
	  		uploader = CacheUploader.new
	  		uploader.cache!(:path)
	  		uploader.retrieve_from_cache!(:path)
		end
	end

end

app/helpers/pages_helper.rb
module PagesHelper

	def home
		@image = Image.new
	end
end

app/helpers/portefolio_helper.rb
module PortefolioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate
    deny_access unless signed_in?
  end

   def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.password_salt]
    self.current_user = user
  end

   def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    @current_user = nil
  end


  private
  
    def user_from_remember_token
     # User.authenticate_with_salt(*remember_token)
     User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    
  def deny_access
    redirect_to log_in_path, :notice => "Please sign in to access this page."
  end

  def current_user?(user)
    user == current_user
  end

  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= hidden_field :image, :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :path%><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_formInit.html.erb
<h2>Upload images now!</h2>
<%= form_for @image, :html => {:multipart => true}, :url => { :controller => "images", :action => "createNoId" } do |f| %>
<div class="field">
    <%= f.file_field :path%><br />
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
  <li class="images">
  	<span class="image"><%= image_tag image.path_url.to_s %>
    <span class="content"><%= image.title %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(image.created_at) %> ago.
    </span>
    
    <div class="actions">
    <span><%= link_to 'Show', image %></span>
    <span><%= link_to 'Edit', edit_image_path(image) %></span>
     <span><%= link_to 'Destroy', image, confirm: 'Are you sure?', method: :delete %></span>
     </div>
  </li>

app/views/images/_imageInit.html.erb
  <li class="images">

<% if !Dir.glob(File.join("public", "uploads/tmp/*")).empty? %>
	<% file = Dir.glob(File.join("public", "uploads/tmp/*")) do |file| %>
			<% pic = Dir.glob(File.join(file, "/*")) do |pic| %>
  					<%= image_tag File.join("/",pic.to_s) %>
  				<%end%>
  		<%end%>
 <%else%>
  	<span class="images">No Images</span>
<%end%>
     
    <div class="actions">
    
     </div>
  </li>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Owner</th>
    <th>Description</th>
    <th>Date</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.title %></td>
    <td><%= image.user_id %></td>
    <td><%= image.description %></td>
    <td><%= image.date %></td>
    <td><%= image.path %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= image_tag @image.path_url.to_s %></p>

<p>
  <b>Title:</b>
  <%= @image.title %>
</p>

<p>
  <b>Owner:</b>
  <%= @image.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @image.description %>
</p>

<p>
  <b>Date:</b>
  <%= @image.date %>
</p>

<p>
  <b>Path:</b>
  <%= @image.path %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', current_user %>

app/views/layouts/_header.html.erb
<header>
 <div id="user_nav">
  <% if signed_in? %>
    <%= link_to "Log out", log_out_path, :method => :delete %>
    <td><%= link_to 'Cancel Account', @user, confirm: 'Are you sure?', method: :delete %></td>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>
</header>

app/views/layouts/_stylesheets.html.erb
 <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginApp</title>
     <%= render 'layouts/stylesheets' %>
</head>
<body>
<div id="container">
<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/pages/admin.html.erb
<h1>Pages#admin</h1>
<p>Find me in app/views/pages/admin.html.erb</p>

app/views/pages/home.html.erb
<% @image = Image.new%>
<%= render :partial => "images/formInit", :object => @image%>

<%= render :partial => "images/imageInit", :object => @image%>

app/views/portefolio/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <!--
    Supersized - Fullscreen Slideshow jQuery Plugin
    Version : 3.2.6
    Site  : www.buildinternet.com/project/supersized
    
    Author  : Sam Dunn
    Company : One Mighty Roar (www.onemightyroar.com)
    License : MIT License / GPL License
  -->

  <head>

    <title>Supersized - Full Screen Background Slideshow jQuery Plugin</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    
    <link rel="stylesheet" href="css/supersized.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="theme/supersized.shutter.css" type="text/css" media="screen" />
    
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.easing.min.js"></script>
    
    <script type="text/javascript" src="js/supersized.3.2.6.js"></script>
    <script type="text/javascript" src="theme/supersized.shutter.min.js"></script>
    
    <script type="text/javascript">
      
      jQuery(function($){
        
        $.supersized({
        
          // Functionality
          slideshow               :   1,      // Slideshow on/off
          autoplay        : 1,      // Slideshow starts playing automatically
          start_slide             :   1,      // Start slide (0 is random)
          stop_loop       : 0,      // Pauses slideshow on last slide
          random          :   0,      // Randomize slide order (Ignores start slide)
          slide_interval          :   3000,   // Length between transitions
          transition              :   6,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
          transition_speed    : 1000,   // Speed of transition
          new_window        : 1,      // Image links open in new window/tab
          pause_hover             :   0,      // Pause slideshow on hover
          keyboard_nav            :   1,      // Keyboard navigation on/off
          performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
          image_protect     : 1,      // Disables image dragging and right click with Javascript
                                 
          // Size & Position               
          min_width           :   0,      // Min width allowed (in pixels)
          min_height            :   0,      // Min height allowed (in pixels)
          vertical_center         :   1,      // Vertically center background
          horizontal_center       :   1,      // Horizontally center background
          fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
          fit_portrait          :   1,      // Portrait images will not exceed browser height
          fit_landscape     :   0,      // Landscape images will not exceed browser width
                                 
          // Components             
          slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
          thumb_links       : 1,      // Individual thumb links for each slide
          thumbnail_navigation    :   0,      // Thumbnail navigation
          slides          :   [ 
          // <% @images.each do |image| %>
          //   <%= @image.path_url.to_s %>
          // <% end %> ],
                        
          // Theme Options         
          progress_bar      : 1,      // Timer for each slide             
          mouse_scrub       : 0
          
        });
        });
        
    </script>
    
  </head>
  
  <style type="text/css">
    ul#demo-block{ margin:0 15px 15px 15px; }
      ul#demo-block li{ margin:0 0 10px 0; padding:10px; display:inline; float:left; clear:both; color:#aaa; background:url('img/bg-black.png'); font:11px Helvetica, Arial, sans-serif; }
      ul#demo-block li a{ color:#eee; font-weight:bold; }
  </style>

<body>

  <!--Demo styles (you can delete this block)-->
  
  <h1>TEST</h1>
  <!--End of styles-->

  <!--Thumbnail Navigation-->
  <div id="prevthumb"></div>
  <div id="nextthumb"></div>
  
  <!--Arrow Navigation-->
  <a id="prevslide" class="load-item"></a>
  <a id="nextslide" class="load-item"></a>
  
  <div id="thumb-tray" class="load-item">
    <div id="thumb-back"></div>
    <div id="thumb-forward"></div>
  </div>
  
  <!--Time Bar-->
  <div id="progress-back" class="load-item">
    <div id="progress-bar"></div>
  </div>
  
  <!--Control Bar-->
  <div id="controls-wrapper" class="load-item">
    <div id="controls">
      
      <a id="play-button"><img id="pauseplay" src="img/pause.png"/></a>
    
      <!--Slide counter-->
      <div id="slidecounter">
        <span class="slidenumber"></span> / <span class="totalslides"></span>
      </div>
      
      <!--Slide captions displayed here-->
      <div id="slidecaption"></div>
      
      <!--Thumb Tray button-->
      <a id="tray-button"><img id="tray-arrow" src="img/button-tray-up.png"/></a>
      
      <!--Navigation-->
      <ul id="slide-list"></ul>
      
    </div>
  </div>

</body>
</html>

app/views/users/new.html.erb
<h1><% @title %></h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<div class="profile">

 
      <% unless @user.images.empty? %>
        <div class="show_image" summary="User images">
          <ul>
            <%= render @images %>
          </ul>
        </div>
      <% end %>
    <div class="sidebar">
      <strong>Name</strong> <%= @user.email %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Images</strong> <%= @user.images.count %>
    </div>
    <div class="clear"></div>
    <%= link_to "Add images", "/images/new" %>
</div>